[[columns]]
kind = "Pid"
style = "Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"
max_width = 6

[[columns]]
kind = "Ppid"
style = "Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"
header = "PPID"
max_width = 6

[[columns]]
kind = "User"
style = "Black"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "CpuTime"
style = "Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "VmRss"
style = "ByUnit"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "ReadBytes"
style = "Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "WriteBytes"
style = "Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Separator"
style = "Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "State"
style = "ByState"
numeric_search = false
nonnumeric_search = false
align = "Left"
max_width = 5

[[columns]]
kind = "Nice"
style = "Magenta"
numeric_search = true
nonnumeric_search = false
align = "Left"
max_width = 5

[[columns]]
kind = "Threads"
style = "Magenta"
numeric_search = true
nonnumeric_search = false
align = "Left"
header = "NLWP"
max_width = 5

[[columns]]
kind = "Tty"
style = "Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Slot"
style = "Red"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Slot"
style = "Red"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Separator"
style = "Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Command"
style = "Black"
numeric_search = false
nonnumeric_search = true
align = "Left"

[style]
header = "Black"
unit = "Black"
tree = "Black"

[style.by_percentage]
color_000 = "Blue"
color_025 = "Green"
color_050 = "Yellow"
color_075 = "Red"
color_100 = "Red"

[style.by_state]
color_d = "Red"
color_r = "Green"
color_s = "Blue"
color_t = "Cyan"
color_z = "Magenta"
color_x = "Magenta"
color_k = "Yellow"
color_w = "Yellow"
color_p = "Yellow"

[style.by_unit]
color_k = "Blue"
color_m = "Green"
color_g = "Yellow"
color_t = "Red"
color_p = "Red"
color_x = "Blue"

[search]
numeric_search = "Exact"
nonnumeric_search = "Partial"
logic = "And"

[display]
show_self = false
cut_to_terminal = true
cut_to_pager = false
cut_to_pipe = false
color_mode = "Auto"
separator = "│"
ascending = "▲"
descending = "▼"
tree_symbols = ["│", "─", "┬", "├", "└"]
abbr_sid = true

[sort]
column = 4
order = "Descending"

[docker]
path = "unix:///var/run/docker.sock"

[pager]
mode = "Always"
detect_width = false
