# /Users/varunshoor/.config/tmuxinator/johari/database.yml

name: johari/database
root: ~/bottomline/johari/database

windows:
  - nvim:
      layout: 2644,231x66,0,0[231x57,0,0,103,231x8,0,58,104]
      panes:
        - nvim .
        -
  - console:
  - git: lazygit
  - production: harlequin --theme solarized-light -a postgres $DB_URL
  - local: harlequin --theme solarized-light -a postgres $DB_URL_DEV
