return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  branch = "main",
  build = ":TSUpdate",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-context",
    "m-demare/hlargs.nvim",
  },
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    context_commentstring = { enable = true, enable_autocmd = false },
    ensure_installed = {
      -- Golang
      "go",
      "gomod",
      "gowork",
      "gosum",
      "bash",
      "html",
      "javascript",
      "json",
      "http",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      -- "yaml",
      "jsdoc",
      "toml",
      "rust",
      "scss",
      "vue",
      "graphql",
      "css",
      "prisma",
      "dockerfile",
      "astro",
      "gitignore",
      "gomod",
      "r",
      "sql",
      "terraform",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<CR>",
        scope_incremental = "<CR>",
        node_incremental = "<noop>",
        node_decremental = "<Backspace>",
      },
    },
    rainbow = {
      enable = true,
    },
    matchup = {
      enable = true,
    },
  },
}
